### ISSUE TITLE
Build Sandmark dependency packages with Multicore OCaml CI

### ISSUE THREAD

**Issue by shakthimaan** [ocurrent/ocaml-multicore-ci#17]
The Sandmark benchmark suite has a number of dependency packages that are needed by the benchmark programs.
- [x] The pinned version of the dependency packages are listed in the `dev.opam` file. It will be useful to know if these packages continue to build using the Multicore OCaml CI.
    https://github.com/ocaml-bench/sandmark/blob/main/dependencies/template/dev.opam
- [x] There are few other `dependencies/packages` that are locally maintained, which we are also upstreaming. If the same can be added to Multicore OCaml CI, it will be useful.
- [x] If there are newer package versions of the above in opam.ocaml.org, we would also like to know if they build fine, so that we can update our dependencies.

**Comment by moyodiallo** [comment]
For the last task you have already OCaml health-check http://check.ocamllabs.io:8080/, where the
lastest version of opam.ocaml.org packages are built.

**Comment by moyodiallo** [comment]
Would you like to create a GitHub repository for the directory `dependencies/packages`,
The GitHub repository has to contains `packages` and the `file repo` like https://github.com/ocaml/opam-repository

It would be easier to integrate them in the CI.

**Comment by shakthimaan** [comment]
> Would you like to create a GitHub repository for the directory dependencies/packages,

I would like to avoid duplicating the data. The `Sandmark` main branch is the source of all truth. Would it be possible to pull the relevant package names and versions dynamically from Sandmark, and use it in multicore-ocaml-ci?

**Comment by moyodiallo** [comment]
I think that can be possible writing a specific plugin for sandmark. I'm gonna try that.
