### ISSUE TITLE
Backport changes from Ewan's fork to ocurrent

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-multicore-ci#19]
These two changes should be PR'd against the main repo:
- [ ] https://github.com/ewanmellor/ocurrent/commit/6f78bc37d8af49b11407f8996cb054f00da8a128
- [ ] https://github.com/ewanmellor/ocurrent/commit/ed64f49dcdb849b8e55d13d185a8ffa9a10c60c4

**Comment by moyodiallo** [comment]
The first one(https://github.com/ewanmellor/ocurrent/commit/6f78bc37d8af49b11407f8996cb054f00da8a128) simply added.

About the second one(https://github.com/ewanmellor/ocurrent/commit/ed64f49dcdb849b8e55d13d185a8ffa9a10c60c4). 
Would you like to look in to those commits, if we gonna add them in ocurrent.
- https://github.com/ewanmellor/ocurrent/commit/58e9912c322519341b083f4ee16941f60aba5f8c branch https://github.com/ewanmellor/ocurrent/tree/cancel-eperm
- https://github.com/ewanmellor/ocurrent/commit/a4b312e3984cde18c65706fe7cf019dc88eed961 branch https://github.com/ewanmellor/ocurrent/tree/diagram-job-markers
 
He merge https://github.com/ewanmellor/ocurrent/tree/ui-restyle branch and I didn't get it.
when do you supposed to use this branch ?

**Comment by tmcgilchrist** [comment]
@moyodiallo Could you try switching this project to use a ocurrent/ocurrent from master?
So we can test that the back ports work in this project and can switch off using Ewan's fork.

**Comment by moyodiallo** [comment]
Done In #21
